export { default as extServiceBackgroundImage } from "./assets/extServiceBackground.jpg";
export { getCollabedHelpComponentConfig } from "./getCollabedHelpComponentConfig";
export { tooltipText } from "./tooltips";
export { extServiceText } from "./ExtService";
export { searchTextPlaceholder } from "./searchTextPlaceholder";
export { mobileInfo } from "./mobileInfo";
export { elements as geoElements } from "./elements";
export { demoElements } from "./demoElements";
export { backgroundSettings } from "./backgroundSettings";
export { additionalInfoFactory } from "./sachdatenabfrage-modals/helper/factory";
